SWM-Retriever/Client

.idea/misc.xml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/retriever/dailypet/LoginActivity.kt
app/src/main/java/org/retriever/dailypet/RegisterProfileActivity.kt
app/src/main/res/drawable/round_button.xml
app/src/main/res/layout/activity_register_profile.xml

- 프로필 등록 페이지 UI
- 라운드 버튼 xml
- 프로필 등록 UI 페이지
- 닉네임 유효 검사 기능
- None

Profile Registeration UI

---

.github/pull_request_template.md
.idea/misc.xml
app/build.gradle
app/src/main/java/org/retriever/dailypet/LoginActivity.kt
app/src/main/java/org/retriever/dailypet/RegisterProfileActivity.kt
app/src/main/res/layout/activity_login.xml
app/src/main/res/values/app_key.xml

- 관련 이슈 : 네이버 토큰 API
- JIRA 백로그 : PET-169
- 관련 문서 : N/A
- 네이버 프로젝트 등록
- 네이버 sdk 설치
- 네이버 로그인 기능
- 네이버 회원정보 조회 테스트 (이름, 이메일)
- 네이버 로그아웃 기능
N/A
- 카카오 로그인과 동작은 동일합니다

Naver Login

---

app/build.gradle
app/src/main/java/org/retriever/dailypet/LoginActivity.kt
app/src/main/java/org/retriever/dailypet/TestActivity.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/java/org/retriever/dailypet/models/User.kt
app/src/main/res/layout/activity_test.xml

- 관련 이슈 : API 통신 메소드 정의
- JIRA 백로그 : PET-171
- 관련 문서 : N/A
- retrofit 환경 구성
- model, interface 구성
- Mock API Test (테스트 페이지)
- Login API Setting
- 로그인 API 테스트 준비되었습니다

Retrofit Setting

---

app/src/main/java/org/retriever/dailypet/LoginActivity.kt
app/src/main/java/org/retriever/dailypet/RegisterProfileActivity.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/java/org/retriever/dailypet/models/User.kt
app/src/main/res/layout/activity_login.xml

- 관련 이슈 : API 연동환경 구축
- JIRA 백로그 : PET-170
- 관련 문서 : N/A
- sns 연동 해제 기능 추가
- 유저정보(이름, 이메일) Post
- 회원 아닐 시 프로필 등록페이지로 이동
- 프로필 등록페이지에 User Info display
N/A
- post로 이름과 이메일 전달예정
- 실패 응답 코드 받을 시 프로필 등록페이지가 보이면 성공

Ready to Login API Interworking

---

app/src/main/java/org/retriever/dailypet/LoginActivity.kt
app/src/main/java/org/retriever/dailypet/RegisterProfileActivity.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/java/org/retriever/dailypet/models/User.kt
app/src/main/res/values-night/themes.xml

- 관련 이슈 : 인앱 갤러리 조회 기능
- JIRA 백로그 : PET-104
- 관련 문서 : N/A
- 로그인 mock API 연동
- 갤러리 조회 기능 추가
- 카메라 / 갤러리 launcher 분리
- None

In App Gallery Function

---

.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/org/retriever/dailypet/LoginActivity.kt
app/src/main/java/org/retriever/dailypet/RegisterProfileActivity.kt
app/src/main/java/org/retriever/dailypet/SelectFamilyType.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/java/org/retriever/dailypet/models/User.kt
app/src/main/res/layout/activity_select_family_type.xml

- 관련 이슈 : 프로필 등록 API 연동
- JIRA 백로그 : PET-102
- 관련 문서 : N/A
- 닉네임 중복 검사 API 연동
- 프로필 등록 API 연동
(닉네임 중복 체크 안할시 프로필 등록 방지)
N/A
- None

Profile Register API Interworking

---

.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/org/retriever/dailypet/FamilyEntranceActivity.kt
app/src/main/java/org/retriever/dailypet/RegisterProfileActivity.kt
app/src/main/java/org/retriever/dailypet/SelectFamilyTypeActivity.kt
app/src/main/res/drawable/rectangle_button.xml
app/src/main/res/layout/activity_family_entrance.xml
app/src/main/res/layout/activity_select_family_type.xml

- 관련 이슈 : 가족 유형 선택 UI
- JIRA 백로그 : PET-109
- 관련 문서 : N/A
- 가족 유형 선택 페이지
- 가족 유형 선택 페이지에서 뒤로가기 금지
- None

Select Family Type UI

---

.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/org/retriever/dailypet/CreateFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/EnterFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/FamilyEntranceActivity.kt
app/src/main/java/org/retriever/dailypet/FindFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/java/org/retriever/dailypet/models/User.kt
app/src/main/res/layout/activity_create_family.xml
app/src/main/res/layout/activity_enter_family.xml
app/src/main/res/layout/activity_find_family.xml

- 관련 이슈 : 초대코드 입력 UI, 초대코드 입력 API 연동, 유효 초대코드 가족 정보 표시
- JIRA 백로그 : PET-114, PET-115, PET-124
- 관련 문서 : N/A
- 초대코드 입력 페이지 UI
- 유효 초대코드 입력시에만 가족 정보 표시
- 가족 정보 다음 페이지에 전달
- None

FindFamily UI & API Interworking

---

.idea/misc.xml
app/src/main/java/org/retriever/dailypet/CreateFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/EnterFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/FindFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/res/layout/activity_create_family.xml
app/src/main/res/layout/activity_enter_family.xml

- 관련 이슈 : 가족 구성원 등록 UI, 가족 입장 API 연동
- JIRA 백로그 : PET-116, PET-117
- 관련 문서 : N/A
- 가족 구성원 등록 UI
- 가족 정보 불러오기
- None

Enter Family Page UI & API Interworking

---

.idea/misc.xml
app/src/main/java/org/retriever/dailypet/CreateFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/CreatePetActivity.kt
app/src/main/java/org/retriever/dailypet/EnterFamilyActivity.kt
app/src/main/res/layout/activity_create_pet.xml

- 관련 이슈 : 반려동물 생성 UI
- JIRA 백로그 : PET-118
- 관련 문서 : N/A
- 반려동물 생성 UI
- 반려동물 생성 액티비티
- None

Create Pet UI

---

.idea/misc.xml
app/src/main/java/org/retriever/dailypet/BreedSearchDialog.kt
app/src/main/java/org/retriever/dailypet/CreateFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/CreatePetActivity.kt
app/src/main/java/org/retriever/dailypet/CreateProfileActivity.kt
app/src/main/java/org/retriever/dailypet/interfaces/BreedListAdapter.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/java/org/retriever/dailypet/models/Breed.kt
app/src/main/res/drawable/edittext_background.xml
app/src/main/res/drawable/radius_dialog.xml
app/src/main/res/layout/activity_create_pet.xml
app/src/main/res/layout/dialog_search_breed.xml
app/src/main/res/layout/item_breed.xml

- 관련 이슈 : 팝업 캘린더 UI, 팝업 검색창 UI
- JIRA 백로그 : PET-127, PET-128
- 관련 문서 : N/A
- 팝업 캘린더 기능 추가
- 품종 검색 기능 추가 (부분 검색)
- 팝업 검색창 아이템 선택에서 오류가 있는데 일단 보류해두었습니다

Pop-up Calendar and Search Dialog

---

app/src/main/java/org/retriever/dailypet/CreateFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/CreatePetActivity.kt
app/src/main/java/org/retriever/dailypet/CreateProfileActivity.kt
app/src/main/java/org/retriever/dailypet/TermOfService.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/res/values/strings.xml

- 관련 이슈 : 반려동물 생성 API 연동
- JIRA 백로그 : PET-130
- 관련 문서 : N/A
- 고화질의 사진 용량을 300*300으로 리사이즈
- MultiPart API 리팩토링
- API 관련 변수들 상수화
- 사진이 없는 경우도 일관성있게 MultiPart 형식으로 전달합니다

Refactor: Image API (MultiPart)

---

app/src/main/java/org/retriever/dailypet/BreedSearchDialog.kt
app/src/main/java/org/retriever/dailypet/CreateFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/CreatePetActivity.kt
app/src/main/java/org/retriever/dailypet/CreateProfileActivity.kt
app/src/main/java/org/retriever/dailypet/interfaces/BreedListAdapter.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/res/layout/activity_create_pet.xml
app/src/main/res/layout/dialog_search_breed.xml

- 관련 이슈 : API 연동 테스트 준비
- JIRA 백로그 : PET-130
- 관련 문서 : N/A
- MultiPart 리팩토링
- Create Pet Activity 바인딩
- 각종 예외처리
- API 테스트 준비 완료되었습니다

Read for API Test

---

.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/org/retriever/dailypet/EnterFamilyActivity.kt
app/src/main/java/org/retriever/dailypet/FamilyEntranceActivity.kt
app/src/main/java/org/retriever/dailypet/FindGroupActivity.kt
app/src/main/res/layout/activity_find_family.xml
app/src/main/res/layout/activity_find_group.xml
app/src/main/res/values/strings.xml

- 관련 이슈 : 그룹 찾기 UI
- JIRA 백로그 : -
- 관련 문서 : N/A
- 그룹 찾기 UI
- 세부 기능 리팩토링
- 그룹 멤버 정보 디스플레이는 추후 논의 후 수정하겠습니다
- 일단은 그룹 정보만 가져오기 (그룹명, 그룹멤버수, 그룹프로필 사진)

Find Group UI Refactoring

---

app/src/main/java/org/retriever/dailypet/fragments/CareFragment.kt
app/src/main/java/org/retriever/dailypet/fragments/HomeFragment.kt
app/src/main/java/org/retriever/dailypet/models/Care.kt
app/src/main/res/drawable/care_progressbar.xml
app/src/main/res/layout/fragment_care.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/values/style.xml

- 관련 이슈 : 챙겨주기 카드 UI, 챙겨주기 등록페이지
- JIRA 백로그 : PET-182
- 관련 문서 : N/A
- 카드 UI 작업
- 탭과 카드 동적 생성 기능 완료
- 챙겨주기 정도에 따라 Progress bar 표시
- 케어 카드 정보 표시
- 메인 페이지 끝이 보입니다..

Dynamic Tab and Card Creation

---

.idea/misc.xml
app/src/main/java/org/retriever/dailypet/RegisterCareActivity.kt
app/src/main/java/org/retriever/dailypet/fragments/CareFragment.kt
app/src/main/java/org/retriever/dailypet/fragments/HomeFragment.kt
app/src/main/res/drawable/small_button_click.xml
app/src/main/res/drawable/small_whiteblue_click_button.xml
app/src/main/res/layout/activity_register_care.xml

- 관련 이슈 : 챙겨주기 등록
- JIRA 백로그 : PET-179
- 관련 문서 : N/A
- 버튼 활성화/비활성화 처리
- 주기 체크박스 생성
- 전 항목 유효성 체크
- None

Add Care Register Contents

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/retriever/dailypet/CreateProfileActivity.kt
app/src/main/java/org/retriever/dailypet/LoginActivity.kt
app/src/main/java/org/retriever/dailypet/StartActivity.kt
app/src/main/java/org/retriever/dailypet/fragments/MyPageFragment.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/java/org/retriever/dailypet/models/App.kt
app/src/main/java/org/retriever/dailypet/models/User.kt
app/src/main/res/values/strings.xml

- 관련 이슈 : API 연동
- JIRA 백로그 : -
- 관련 문서 : N/A
- API 연동 테스트 완료
- 연동 API 첫 테스트 성공했습니다

Back-end Interworking Setting

---

app/src/main/java/org/retriever/dailypet/CreateProfileActivity.kt
app/src/main/java/org/retriever/dailypet/LoginActivity.kt
app/src/main/java/org/retriever/dailypet/TermOfServiceActivity.kt
app/src/main/java/org/retriever/dailypet/interfaces/RetrofitService.kt
app/src/main/java/org/retriever/dailypet/models/App.kt
app/src/main/java/org/retriever/dailypet/models/User.kt

- 관련 이슈 : API 연동 (프로필 등록)
- JIRA 백로그 : -
- 관련 문서 : 
- 닉네임 검증
- 프로필 등록
- 이미지 데이터 null값 여부는 추후 의논해봐야할 것 같습니다

API Setting: Register Profile

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/retriever/dailypet/BreedSearchDialog.kt
app/src/main/java/org/retriever/dailypet/CreateProfileActivity.kt
app/src/main/java/org/retriever/dailypet/MainActivity.kt
app/src/main/java/org/retriever/dailypet/RegisterCareActivity.kt
app/src/main/java/org/retriever/dailypet/StartActivity.kt
app/src/main/java/org/retriever/dailypet/fragments/HomeFragment.kt
app/src/main/java/org/retriever/dailypet/interfaces/MyFirebaseMessagingService.kt
build.gradle

- 관련 이슈 : FCM
- JIRA 백로그 :
- 관련 문서 : 
- FCM Setting
- Device Token Setting
- 파이어베이스 기반의 device token 값 세팅입니다

FCM Setting

---

app/src/main/java/org/retriever/dailypet/CreateProfileActivity.kt
app/src/main/java/org/retriever/dailypet/LoginActivity.kt
app/src/main/java/org/retriever/dailypet/StartActivity.kt
app/src/main/java/org/retriever/dailypet/interfaces/MyFirebaseMessagingService.kt
app/src/main/java/org/retriever/dailypet/models/App.kt

- 관련 이슈 : Shared Preference Set
- JIRA 백로그 :
- 관련 문서 : 
- Device Token set
- None

FCM: Shared Preference Setting

---

.idea/misc.xml
app/src/main/java/org/retriever/dailypet/GlobalApplication.kt
app/src/main/java/org/retriever/dailypet/data/network/signup/PetApiService.kt
app/src/main/java/org/retriever/dailypet/data/repository/signup/PetRepository.kt
app/src/main/java/org/retriever/dailypet/model/signup/pet/Pet.kt
app/src/main/java/org/retriever/dailypet/model/signup/pet/PetInfo.kt
app/src/main/java/org/retriever/dailypet/model/signup/pet/PetResponse.kt
app/src/main/java/org/retriever/dailypet/ui/bottomsheet/BreedBottomSheet.kt
app/src/main/java/org/retriever/dailypet/ui/login/LoginFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/MainActivity.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreatePetFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreationCompleteFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/viewmodel/PetViewModel.kt
app/src/main/res/layout/fragment_create_family.xml
app/src/main/res/navigation/login_navigation_graph.xml
app/src/main/res/values/strings.xml

- 관련 이슈 : Refactoring
- JIRA 백로그 :
- 관련 문서 : 
- Pet ID Get Logic
- CreatePetSubmit Function
- CreateCompletion Fragment
- None

Refactoring

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/retriever/dailypet/di/NetworkModule.kt
app/src/main/java/org/retriever/dailypet/ui/signup/FindGroupFragment.kt
app/src/main/res/layout/fragment_find_group.xml
app/src/main/res/layout/item_family.xml
app/src/main/res/values/strings.xml

- 관련 이슈 : 
- 관련 문서 : 
- refactoring : FindGroupFragment
- None

refactoring : FindGroupFragment

---

app/src/main/java/org/retriever/dailypet/GlobalApplication.kt
app/src/main/java/org/retriever/dailypet/ui/login/LoginFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/HomeFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/MainActivity.kt
app/src/main/java/org/retriever/dailypet/ui/mypage/MyPageMainFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreationCompleteFragment.kt

- 관련 이슈 : 
- 관련 문서 : 
- fix : PetList Sharedpreference Save -> Not save
- None

[PR] fix : PetList Sharedpreference Save -> Not save

---

app/src/main/java/org/retriever/dailypet/data/network/main/HomeApiService.kt
app/src/main/java/org/retriever/dailypet/data/network/signup/FindGroupApiInterface.kt
app/src/main/java/org/retriever/dailypet/data/repository/main/HomeRepository.kt
app/src/main/java/org/retriever/dailypet/model/login/LoginResponse.kt
app/src/main/java/org/retriever/dailypet/model/signup/pet/PetList.kt
app/src/main/java/org/retriever/dailypet/ui/main/AddCareFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/CareFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/HomeFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/viewmodel/HomeViewModel.kt
app/src/main/res/layout/fragment_care.xml
app/src/main/res/values/strings.xml

- 관련 이슈 : 
- 관련 문서 : 
- 가족입장할때 가족내닉네임 오류 수정
- 케어 추가하기 오류 수정
- 체크, 체크취소 API 연동
- 케어삭제 API 연동
- 케어 삭제, 수정 메뉴 뷰
- 케어 리팩토링
- 체크시 다른 카드뷰에 프로그레스바가 올라가는 오류 있습니다 (뷰모델 이슈)

[PR] Care Refactoring && Check Cancel API

---

app/src/main/java/org/retriever/dailypet/model/mypage/PetDetailItem.kt
app/src/main/java/org/retriever/dailypet/model/signup/family/ModifyFamilyResponse.kt
app/src/main/java/org/retriever/dailypet/model/signup/pet/ModifyPetRequest.kt
app/src/main/java/org/retriever/dailypet/model/signup/pet/ModifyPetResponse.kt
app/src/main/java/org/retriever/dailypet/model/signup/pet/PetInfo.kt
app/src/main/java/org/retriever/dailypet/model/signup/pet/PetResponse.kt
app/src/main/java/org/retriever/dailypet/ui/main/MainActivity.kt
app/src/main/java/org/retriever/dailypet/ui/mypage/detail/MyPageDetailViewModel.kt
app/src/main/java/org/retriever/dailypet/ui/mypage/detail/MyPagePetDetailFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreateFamilyFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreatePetFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreationCompleteFragment.kt
app/src/main/res/values/strings.xml

- 관련 이슈 : 
- 관련 문서 : 
- I think finish mypage
- None

I think finish mypage

---

app/src/main/java/org/retriever/dailypet/data/network/main/HomeApiService.kt
app/src/main/java/org/retriever/dailypet/data/network/signup/PetApiService.kt
app/src/main/java/org/retriever/dailypet/data/repository/main/HomeRepository.kt
app/src/main/java/org/retriever/dailypet/data/repository/signup/PetRepository.kt
app/src/main/java/org/retriever/dailypet/model/login/LoginResponse.kt
app/src/main/java/org/retriever/dailypet/model/signup/pet/PetResponse.kt
app/src/main/java/org/retriever/dailypet/ui/main/CareAdapter.kt
app/src/main/java/org/retriever/dailypet/ui/main/CareFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/HomeFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/viewmodel/HomeViewModel.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreateFamilyFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreatePetFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreationCompleteFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/viewmodel/PetViewModel.kt
app/src/main/res/drawable/arrlow_down_customize.xml
app/src/main/res/layout/fragment_care.xml
app/src/main/res/layout/fragment_home.xml

- 관련 이슈 : 
- 관련 문서 : 
- Refactoring
- Care View
- API Refactoring
- None

[PR] Ver 0.2

---

app/build.gradle
app/src/main/java/org/retriever/dailypet/data/network/main/HomeApiService.kt
app/src/main/java/org/retriever/dailypet/data/repository/main/HomeRepository.kt
app/src/main/java/org/retriever/dailypet/model/main/GroupInfo.kt
app/src/main/java/org/retriever/dailypet/ui/main/CareFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/HomeFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/HomeViewModel.kt
app/src/main/res/layout/fragment_care.xml
app/src/main/res/layout/fragment_select_family_type.xml
app/src/main/res/values/colors.xml

- 관련 이슈 : 
- 관련 문서 : 
- Import stateProgressBar
- Custom stateProgressBar
- None

[PR] Create ProgressBar

---

app/src/main/java/org/retriever/dailypet/model/signup/pet/PetResponse.kt
app/src/main/java/org/retriever/dailypet/ui/main/CareFragment.kt
app/src/main/java/org/retriever/dailypet/ui/main/HomeFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreationCompleteFragment.kt
app/src/main/java/org/retriever/dailypet/ui/splash/SplashActivity.kt
app/src/main/res/layout/fragment_care.xml
app/src/main/res/layout/fragment_home.xml

- 관련 이슈 : 
- 관련 문서 : 
- 챙겨주기 끝
- 새로 고침 인덱스
- 혼자키워요 오류 수정
- 카카오 로그인 유지
- None

[PR] Care Complete && Bug Fix

---

app/src/main/java/org/retriever/dailypet/data/network/signup/FindGroupApiInterface.kt
app/src/main/java/org/retriever/dailypet/data/repository/signup/FindGroupRepository.kt
app/src/main/java/org/retriever/dailypet/model/signup/family/EnterFamilyResponse.kt
app/src/main/java/org/retriever/dailypet/ui/bottomsheet/AddProfileBottomSheet.kt
app/src/main/java/org/retriever/dailypet/ui/mypage/MyPageMainFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreationCompleteFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/viewmodel/FindGroupViewModel.kt

- 관련 이슈 : 
- 관련 문서 : 
- 
- None

Fix: Enter Group Family ID Bug

---

app/build.gradle
app/src/main/java/org/retriever/dailypet/data/network/presignedurl/PreSignedUrlApiService.kt
app/src/main/java/org/retriever/dailypet/data/network/signup/ProfileApiService.kt
app/src/main/java/org/retriever/dailypet/data/repository/presignedurl/PreSignedUrlRepository.kt
app/src/main/java/org/retriever/dailypet/di/NetworkModule.kt
app/src/main/java/org/retriever/dailypet/di/RepositoryModule.kt
app/src/main/java/org/retriever/dailypet/model/presignedurl/PreSignedUrlResponse.kt
app/src/main/java/org/retriever/dailypet/ui/home/statistics/StatisticsViewModel.kt
app/src/main/java/org/retriever/dailypet/ui/mypage/adapter/GroupAdapter.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreateProfileFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/viewmodel/ProfileViewModel.kt
app/src/main/java/org/retriever/dailypet/ui/splash/SplashActivity.kt
app/src/main/java/org/retriever/dailypet/util/RotateBitmap.kt

- 관련 이슈 : 
- 관련 문서 : 
- 
- None

feat : Implementation camera

---

app/src/main/java/org/retriever/dailypet/data/network/home/HomeApiService.kt
app/src/main/java/org/retriever/dailypet/data/network/home/StatisticsApiService.kt
app/src/main/java/org/retriever/dailypet/data/network/signup/PetApiService.kt
app/src/main/java/org/retriever/dailypet/data/repository/home/HomeRepository.kt
app/src/main/java/org/retriever/dailypet/model/main/MyContributionResponse.kt
app/src/main/java/org/retriever/dailypet/model/signup/pet/PetInfo.kt
app/src/main/java/org/retriever/dailypet/ui/home/care/AddCareFragment.kt
app/src/main/java/org/retriever/dailypet/ui/home/care/HomeMainFragment.kt
app/src/main/java/org/retriever/dailypet/ui/home/care/HomeViewModel.kt
app/src/main/java/org/retriever/dailypet/ui/home/care/ModifyCareFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreatePetFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreateProfileFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/viewmodel/PetViewModel.kt
app/src/main/res/layout/fragment_add_care.xml
app/src/main/res/layout/fragment_modify_care.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml

- 관련 이슈 : 
- 관련 문서 : 
- s3 api 세팅
- 카메라 커스텀 라이브러리 (크롭 편집 기능)
- 기여도 API 연동
- 커스텀 카운트 설정 (케어 횟수 1~10)
- None

[PR] Pre-Signed URL && Contribution API && Custom Count

---

app/src/main/java/org/retriever/dailypet/data/network/presignedurl/PreSignedUrlApiService.kt
app/src/main/java/org/retriever/dailypet/data/repository/presignedurl/PreSignedUrlRepository.kt
app/src/main/java/org/retriever/dailypet/ui/mypage/adapter/PetAdapter.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreatePetFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/CreateProfileFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/viewmodel/PetViewModel.kt
app/src/main/java/org/retriever/dailypet/ui/signup/viewmodel/ProfileViewModel.kt

- 관련 이슈 : 
- 관련 문서 : 
- 제발되라되라
- None

제발되라 시발넌ㅁ아

---

app/build.gradle
app/src/main/java/org/retriever/dailypet/ui/mypage/MyPageMainFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/firstcourse/CreateProfileFragment.kt
app/src/main/java/org/retriever/dailypet/ui/signup/firstcourse/NickNameViewState.kt
app/src/main/java/org/retriever/dailypet/ui/signup/firstcourse/ProfileViewModel.kt
app/src/main/java/org/retriever/dailypet/ui/signup/firstcourse/TermOfServiceFragment.kt
app/src/main/res/layout/fragment_create_profile.xml
app/src/main/res/layout/fragment_my_page_main.xml
app/src/main/res/layout/fragment_term_of_service.xml
app/src/main/res/navigation/login_navigation_graph.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/style.xml

- 관련 이슈 : 
- 관련 문서 : 
- Refactoring signup flow first
- None

[PR]Refactoring signup flow first

---

app/build.gradle
app/proguard-rules.pro

- 관련 이슈 : 
- 관련 문서 : 
- Build.gradle
- proguard-rules.pro
- None

[PR] Build Variants && Proguard-rules

---

app/src/main/java/org/retriever/dailypet/ui/signup/pet/PetViewModel.kt

- 관련 이슈 : 
- 관련 문서 : 
- Fix : createpetfragment
- None

[PR] Fix : createpetfragment

---

app/src/main/java/org/retriever/dailypet/ui/home/care/HomeMainFragment.kt
app/src/main/java/org/retriever/dailypet/ui/login/LoginActivity.kt
app/src/main/java/org/retriever/dailypet/ui/login/LoginFragment.kt
app/src/main/java/org/retriever/dailypet/ui/splash/SplashActivity.kt
app/src/main/res/layout/fragment_my_page_main.xml
app/src/main/res/values/strings.xml

- 관련 이슈 : 
- 관련 문서 : 
- 앱 종료 로직 추가
- 자동 로그인 추가 및 오류 수정 (카카오, 네이버)
- 마이페이지 텍스트뷰 수정
- None

[PR] Release 1.4 Fix 

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/retriever/dailypet/ui/home/care/HomeMainFragment.kt
app/src/main/java/org/retriever/dailypet/ui/mypage/MyPageMainFragment.kt
app/src/main/java/org/retriever/dailypet/ui/mypage/adapter/ProfileModifyBottomSheet.kt
app/src/main/java/org/retriever/dailypet/ui/mypage/detail/PetModifyFragment.kt

- 관련 이슈 : 
- 관련 문서 : 
- 프로필, 반려동물 정보 수정 Bug FIx
- 세로모드 고정
- 인앱 리뷰 기능 추가
- None

[PR] Release 1.0.4
